import type { SupabaseClient } from "@supabase/supabase-js";
export declare const BOARD_HOURLY_POST_LIMIT = 10;
export declare const BOARD_HOURLY_COMMENT_LIMIT = 30;
export declare const BOARD_HOURLY_IMAGE_LIMIT = 60;
export declare const NOTICE_COMMENT_HOURLY_LIMIT = 30;
export declare const SUGGESTION_HOURLY_LIMIT = 10;
export declare const SUGGESTION_COMMENT_HOURLY_LIMIT = 30;
export declare const HOURLY_LIMIT_ERROR = "\uC9E7\uC740 \uC2DC\uAC04 \uB3D9\uC548 \uB108\uBB34 \uB9CE\uC774 \uC791\uC131\uD588\uC5B4\uC694. \uC7A0\uC2DC \uD6C4 \uB2E4\uC2DC \uC2DC\uB3C4\uD574\uC8FC\uC138\uC694.";
export type HourlyLimitTable = "board_posts" | "board_comments" | "notice_comments" | "suggestions" | "suggestion_comments";
export declare function overHourlyLimit(client: SupabaseClient, table: HourlyLimitTable, userId: string, limit: number, now?: Date): Promise<boolean>;
